language: php

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

# Note: we explicitly use a 'symfony 3' scenario here because we
# pin to Symfony Console 3.2.2 in our composer.lock for Apveyor testing.
# We can remove this once we fix the whitespace problem in the Windows tests.
matrix:
  include:
    - php: 7.3
      env: 'DEPENDENCIES=highest'
    - php: 7.2
    - php: 7.1
    - php: 7.1
      env: 'DEPENDENCIES=lowest'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - './.scenarios.lock/install "${SCENARIO}" "${DEPENDENCIES}"'

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/coveralls -v
